---
title: "Government Yields"
output: html_notebook
---

### Initialize environment
```{r}
library(caim)
caim::clr()
```
### Setup preferences
```{r}
# most important maturities
maturities_a = c(.25, 2, 5, 10)
# interesting maturities, level b
maturities_b = c(1, 30)
# all other maturities will be level c

# relative weightings for each maturity level
# these will form a density function that will be normalised to sum to 1
#   , so don't worry about that here
MAT_A_WT = 1
MAT_B_WT = .75
MAT_C_WT = 0.15

# set of maturities to use for lambda values
lambda_maturities <- seq(0.5, 5, 0.5)

```

### Load US yields
```{r}
fredr::fredr_set_key(caim::API_KEY_FREDR)
yield_info <- fread("../data/yield_info.csv")
yield_data <- rbindlist(lapply(yield_info$ticker, function(x) data.table(fredr::fredr(x, observation_start = as.Date("1920-01-01")))))

setkeyv(yield_info, "ticker")
setkeyv(yield_data, c("series_id", "date", "value"))

curve_data <- setorderv(
  dcast(yield_info[yield_data, ][, !c("ticker", "source"), with=F]
        , curve_id + country + class_name + sector_name + date ~ maturity
        , value.var="value"
        )
  , cols=c("curve_id", "date")
)
curve_mat_names <- as.character(sort(unique(yield_info$maturity)))
# remove rows when all maturity values are NA
curve_data <- curve_data[apply(curve_data, 1, function(x) !(sum(!is.na(x[curve_mat_names]))==0))]
colnames(curve_data)[colnames(curve_data) %in% curve_mat_names] <- paste0("yield_", curve_mat_names)

```

```{r}
curve_coefs <- list()
curve_ids <- sort(unique(curve_data$curve_id))
for (c in curve_ids) {
  t_curve_data <- curve_data[curve_id == c]
  t_curve_dates <- sort(unique(t_curve_data$date))
  t_curve_mats <- sort(unique(yield_info[curve_id==c]$maturity))
  t_curve_mat_names <- as.character(t_curve_mats)
  
  t_curve_mat_wts <- rep(MAT_C_WT, length(t_curve_mats))
  names(t_curve_mat_wts) <- t_curve_mat_names
  t_curve_mat_wts[names(t_curve_mat_wts) %in% maturities_a] <- MAT_A_WT
  t_curve_mat_wts[names(t_curve_mat_wts) %in% maturities_b] <- MAT_B_WT
  t_curve_mat_wts <- t_curve_mat_wts / sum(t_curve_mat_wts)
  
  
  t_res <- list()
  for (i in 1:length(lambda_maturities)) {
    mat <- lambda_maturities[i]
    lambda <- caim::ns_mat2lambda(mat)
    print(paste("calculating for curve:", c, "maturity:", mat, "lambda:", lambda))
    t_res[[i]] <- list(
      mat=mat
      , lambda=lambda
      , coefs=data.table(
        date=t_curve_data[,date]
        , t(apply(t_curve_data, 1, function(x) 
          caim::ns_yields2coefs(t_curve_mats
                                , as.numeric(x[t_curve_mat_names])
                                , lambda=lambda
                                , wts=t_curve_mat_wts)))))
  }
  
  # calculate summaries
  # 5 year halflife assuming 260 business days in a year
  decay <- halflife2decay(5*260)
  lambda_summary <- data.table(t(sapply(t_res, function(x) 
    c(mat=x$mat, lambda=x$lambda, wss=mean(x$coefs$wss), wss_exp=mean_exp(x$coefs$wss, decay)))))

  # choose best data
  best_hist_fit <- which(lambda_summary$wss == min(lambda_summary$wss))
  best_exp_fit <- which(lambda_summary$wss_exp == min(lambda_summary$wss_exp))
  # take average of best fits, but tilt towards best_exp_fit
  best_ix <- floor(mean(c(best_hist_fit, best_exp_fit))+ifelse(best_exp_fit > best_hist_fit, 0.5, 0))
  best_hist_coefs <- t_res[[best_ix]]
  best_hist_coefs$curve_id <- c

  #add data to curve_coefs
  curve_coefs[[length(curve_coefs)+1]] <- best_ist_coefs
}

```

### Monthly yield curves
```{r}
monthly_coefs <- curve_coefs[[1]]$coefs[date %in% caim::month_end_dates(date)]
coefs_12 <- monthly_coefs[nrow(monthly_coefs) - (12:0)]

dates_12 <- coefs_12$date
mats_12 <- c(.0833, seq(0.25, 30, 0.25))
yields_12 <- data.table(t(sapply(1:nrow(coefs_12), function(x) caim::ns_coefs2yields(coefs_12[x], mats_12)$y)))
colnames(yields_12) <- as.character(mats_12)

colors_12 <- caim::caim_colors("dark1", seq(0.2, 0.7, length.out=length(dates_12)))
colors_12[substr(dates_12, 6, 7) == 12] <- caim::caim_colors("darkred", 1)
colors_12[length(colors_12)] <- caim::caim_colors("darkblue", 1)
  
lwd_12 <- seq(0.5, 2.5, length.out = length(dates_12))
# lwd_12[length(lwd_12)] <- 2

caim::reset_graphics()
caim::chart_plot(
  range(mats_12)
  , range(yields_12)
  , main="US Govt Yield Curve Changes Over Past 12 Months"
  , xfmt=c("dec", 0)
  , yfmt=c("dec", 2)
  , xlab = "Maturity (years)"
  , ylab = "Yield (pct)"
  , source = "St. Louis Fed, CAIM"
  )

for (i in 1:length(dates_12)) {
  lines(mats_12, yields_12[i,], col=colors_12[i], lwd=lwd_12[i])
}

point_mats <- c(0.25, 2, 5, 10, 30)
point_mat_columns <- as.character(point_mats)
point_yields <- curve_data[nrow(curve_data), ..point_mat_columns]
points(point_mats, point_yields, pch=19, col=colors_12[length(colors_12)])
caim::reset_graphics()
```

### Quarterly changes
```{r}
yields <- curve_data[,c("date", '2')]
colnames(yields) <- c("date", "yield")
yields <- yields[!is.na(yield)]
yields_q <- yields[(date %in% caim::quarter_end_dates(date))]

# calculate yield changes
# absolute basis point change
yield_changes_q <- yields_q$yield[-1] - yields_q$yield[-nrow(yields_q)]
# proportiional change: pct of previous yield
yield_pct_q <- yields_q$yield[-1] / yields_q$yield[-nrow(yields_q)] - 1
```

### Quarterly changes charts
```{r}
# format x axis information
dates_q <- yields_q$date[-1] # because return series will not have t0 date
# get year end dates
xat <- lubridate::as_date(caim::year_end_dates(dates_q))
# only keep dates where we have a december number
xat <- xat[substr(xat, 6, 7) == 12] 
# make "pretty": tick every 5 years
xat <- xat[rev(seq(length(xat), 1, -5))]
# format: 2019Q4 -> 2020, start of new year
xlabels <- lubridate::year(xat) + 1

# format yat
yat_pct <- seq(-1, .75, .25)

caim::reset_graphics()

caim::chart_plot(
  yields_q$date[-1]
  , yield_changes_q
  , showxaxis=T
  , xat=year(yields_q$date)
  , xfmt = c("dec", 0)
  )
points(yields_q$date[-1], yield_changes_q, pch=19, col=caim::caim_colors(1))

caim::chart_plot(
  main="US Govt 2 Year Yield QoQ Changes"
  , cex.main=1
  , xdata=dates_q
  , ydata=yat_pct
  , showxaxis=T
  , xat=xat
  , xaxistext=xlabels
  , xfmt = "txt"
  , yat = yat_pct
  , yfmt = c("pct", 0)
  , ylab = "Proportional Change from Previous Yield"
  , col.lab = caim::caim_colors("dark1")
  , cex.lab = 0.9
  , source="St. Louis Fed, CAIM"
  )
for (i in 1:length(yield_pct_q)) {
  lines(
    c(dates_q[i], dates_q[i])
    , c(0, yield_pct_q[i])
    , col=caim::caim_colors("ash")
  )
}
points(yields_q$date[-1], yield_pct_q, pch=19, col=caim::caim_colors(1))
caim::reset_graphics()
```

### Historic returns
```{r}
return_mats <- c(0.25, 1, 2, 3, 5, 7, 10)
mat_names <- as.character(return_mats)
coefs_m <- curve_coefs[[1]]$coefs[date %in% caim::month_end_dates(date)]
setkey(coefs_m, date)
dates_m <- coefs_m$date

buy_yields <- data.table(t(sapply(1:(nrow(coefs_m)-1), function(x) caim::ns_coefs2yields(coefs_m[x], return_mats)$y)))
colnames(buy_yields) <- as.character(return_mats)

sell_yields <- data.table(t(sapply(2:nrow(coefs_m), function(x) caim::ns_coefs2yields(coefs_m[x], return_mats - 1/12)$y)))
colnames(sell_yields) <- as.character(return_mats)

sell_returns <- matrix(0, nrow(buy_yields), ncol(buy_yields))
for (d in 1:nrow(sell_prices)) {
  for (m in 1:ncol(sell_prices)) {
    mat <- as.character(return_mats[m])
    sell_returns[d, m] <- caim::bond_price(as.numeric(sell_yields[d, ..mat]/100)
                                          , as.numeric(buy_yields[d, ..mat]/100)
                                          , return_mats[m] - 1/12
                                          , 2
                                          , 100) / 100
  }
}

coupon_income <- buy_yields / 1200

total_return <- coupon_income + sell_returns

```

### US 1-3 Year return analysis
```{r}
assetdata <- fread("./data/assetdata.csv")
usg13 <- na.omit(assetdata[
  id=="US.GOVT.13"
  ][
    date >= "1977-06-30"
    ][
      , .(
        date=lubridate::as_date(date)
        , year=year(date)
        , month=month(date)
        , index_id=id
        , index_nav=PX_LAST
        )
      ][date %in% caim::month_end_dates(date)
        , index_ret := round((index_nav / shift(index_nav)) - 1, 6)
      ])

ns_return_components_m <- CJ(
  date=coefs_m$date
  , mat=data.table(mat=return_mats)$mat
  )[coefs_m
    ][order(mat, date)
      , .(date, mat, beta0, beta1, beta2, lambda)
      ][
        , yield := caim::ns_coefs2yields(NULL, mat, beta0, beta1, beta2, lambda)$y
        ][
          , prev_yld := ifelse(mat==shift(mat), shift(yield), NA)
          ][
            , yield_sell := caim::ns_coefs2yields(NULL, mat - 1/12, beta0, beta1, beta2, lambda)$y
            ][
              , yield_diff := yield_sell - prev_yld
              ][
                , .(date, mat, yield, prev_yld, yield_sell, yield_diff)
                ][
                  , coup_inc := round(prev_yld / 1200, 6)
                  ][
                    , price_inc := 
                      round(caim::bond_price(yield_sell/100, prev_yld/100, mat - 1/12, 2, 1), 6)
                    ][
                      , tot_ret := coup_inc + price_inc - 1
                      # ][
                      # , .(date, mat, yield, prev_yld, yield_sell, coup_inc, price_inc)
                      ]

ns_returns_x_cols <- as.character(sort(unique(ns_return_components_m$mat)))
ns_returns_x <- na.omit(dcast(ns_return_components_m, date ~ mat, value.var="tot_ret"))[
  , year := lubridate::year(date)
][
  , month := lubridate::month(date)
]

setkeyv(usg13, c("year", "month"))
setkeyv(ns_returns_x, c("year", "month"))

usg13_data <- usg13[ns_returns_x, nomatch=0][
  , !c("year", "month", "index_id", "index_nav", "i.date")
]
y <- usg13_data$index_ret
x2 <- usg13_data[,'2']
X <- usg13_data[, c("1", "2", "3")]

model_2 <- lm(y ~ as.matrix(x2))
model_2_custom <- model_2
model_2_custom$coefficients <- c('(Intercept)'=0, 'x2'=1)
model_linear <- glm(y ~ as.matrix(X))
decay <- caim::halflife2decay(5 * 12)
model_exp <- glm(y ~ as.matrix(X), weights=caim::d_exp(decay, length(y)))

yhat_2 <- predict(model_2)
yhat_2_custom <- predict(model_2_custom)#, newdata=data.frame(x2))
yhat_linear <- predict(model_linear)
yhat_exp <- predict(model_exp)

err_linear <- yhat_linear - y
err_exp <- yhat_exp - y

```


