---
title: "R Notebook"
output: html_notebook
---

```{r}
caim::clr()

tdt <- data.table(
  country = rep("US", 10)
  , date = c(rep(lubridate::as_date("2020-04-09"), 10), rep(lubridate::as_date("2020-04-10"), 10))
  , maturity = rep(c(.0833, 0.25, 0.5, 0.75, 1, 2, 3, 5, 7, 10), 2)
  , yield = c(0.25, 0.3, NA, NA, NA, 0.5, NA, 0.75, NA, 0.9
              , 0.20, NA, NA, NA, 0.35, 0.4, NA, 0.6, NA, 0.8
              )
)
```

```{r}
curve_lin <- function(xy, x=xy$x, expanded=F) {
  
  # filter - keep only valid xys
  xy_valid <- xy[!is.na(y)][ , c("x_orig", "y_orig") := .(x, y)]

  # set up xy_all
  x_all <- data.table(x=sort(unique(c(xy$x, x))))
  xy_all <- merge(xy, x_all, keyby="x", all=T)
  
  # extrapolation parameters for use later
  nx <- nrow(xy_valid)
  x_min <- xy_valid[1, x]
  y_min <- xy_valid[1, y]
  x_min_hi <- xy_valid[2, x]
  y_min_hi <- xy_valid[2, y]
  x_max <- xy_valid[nx, x]
  y_max <- xy_valid[nx, y]
  x_max_lo <- xy_valid[nx - 1, x]
  y_max_lo <- xy_valid[nx - 1, y]
  
  # set up x_lo and x_hi
  xy_lo <- xy_valid[xy_all, .(x, x_lo=x_orig, y_lo=y_orig), on=.(x), roll=T]
  xy_hi <- xy_valid[xy_all, .(x, x_hi=x_orig, y_hi=y_orig), on=.(x), roll=-Inf]
  
  # merge xy_lo and xy_hi
  xy_lin <- xy_hi[
    xy_lo
    , .(
      x, x_lo, x_hi, y_lo, y_hi
    )
    , on=.(x)
  ][
    # set up extrapolation parameters for x < x_lo
    is.na(x_lo)
    , c("x_lo", "y_lo", "x_hi", "y_hi") :=
      .(x_min, y_min, x_min_hi, y_min_hi)
  ][
    # set up extrapolation parameters for x > x_hi
    is.na(x_hi)
    , c("x_lo", "y_lo", "x_hi", "y_hi") :=
      .(x_max_lo, y_max_lo, x_max, y_max)
  ][
    # linear interpolation
    , y := ifelse(x_hi == x_lo, y_lo, y_lo + (x - x_lo) * (y_hi - y_lo) / (x_hi - x_lo))
  ][
    # moderate extrapolated values: average of extrapolated value and y_lo
    x_lo > x
    , y := mean(c(y, y_lo))
    , by=.(x)
  ][
    # moderate extrapolated values: average of extrapolated value and y_hi
    x_hi < x
    , y := mean(c(y, y_hi))
    , by=.(x)
  ]

  if (expanded)
    data.table(x=sort(x))[xy_lin, on=.(x), nomatch=NULL][]
  else
    data.table(x=sort(x))[xy_lin, .(x, y), on=.(x), nomatch=NULL][]
    
}
```


```{r}
# table with !is.na(yield)
yields_valid <- tdt[!is.na(yield)][, c("mat", "yld") := .(maturity, yield)]
# table mapping to <=
yields_lo <- yields_valid[tdt, .(country, date, maturity, m_lo=mat, y_lo=yld), on=.(country, date, maturity), roll=T]
# table mapping to >=
yields_hi <- yields_valid[tdt, .(country, date, maturity, m_hi=mat, y_hi=yld), on=.(country, date, maturity), roll=-Inf]

yields_lin <- yields_hi[
  yields_lo
  , .(
    country
    , date
    , maturity
    , yield_lin = ifelse(m_hi == m_lo
                         , y_hi
                         , y_lo + (maturity - m_lo) * (y_hi - y_lo) / (m_hi - m_lo)
                         )
    , y_hi
    , y_lo
    , m_hi
    , m_lo
  )
  , on=.(country, date, maturity)
]

yields_lin[]
```

